import { useState } from "react";

const Services=()=>{
    useState(
        [
            {
            id:1,
            title:'Java Development',
            description:`Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod eaque, incidunt dignissimos temporibus quos repudiandae eveniet. Tenetur doloribus autem eaque, animi doloremque alias! Modi dolor laboriosam enim fugiat? Libero, vel.</span><span>Recusandae fugiat quidem nulla distinctio consequatur inventore repellendus cupiditate atque suscipit blanditiis, excepturi soluta. Consequatur, sunt harum? Minus ut dicta omnis, libero ratione facere tempora saepe laboriosam, officiis possimus vero.</span><span>Eligendi, et doloremque molestias rerum itaque nisi consequatur eos ut, sunt doloribus in mollitia sapiente maiores aliquam quas ipsam maxime sequi consectetur quo ab magni pariatur laboriosam fuga? Sapiente, animi.</span><span>Animi corrupti culpa exercitationem quasi corporis, aut itaque ipsam quod voluptates voluptatem dicta eum temporibus cupiditate quam non sunt tempore porro assumenda nostrum debitis! Enim quasi aspernatur aliquid maiores illo?</span><span>Hic ab laudantium ratione voluptas architecto modi quisquam cumque officiis perferendis illum dignissimos quod est magni accusamus nostrum, facere eligendi non ut quia veritatis nihil saepe placeat eveniet nam. Illum.</span><span>Similique repellendus dolore, sunt temporibus provident id cupiditate vitae officiis quisquam, sequi alias! Quibusdam aspernatur, possimus illo sit itaque, minima consequuntur assumenda numquam, odio deleniti alias perferendis voluptatum quas officia.</span><span>Amet ipsam corrupti asperiores ipsa. Sunt commodi dolores eos? Voluptatibus recusandae nihil nulla dolore? Minima assumenda obcaecati earum magni itaque ea id similique, tenetur ullam laborum, esse iusto praesentium voluptas?</span><span>Iusto aliquid, nobis nam sit quia sunt, dolorum accusamus officiis magni molestiae qui, nostrum error maxime quis atque cum optio consequatur cupiditate amet ab quisquam quasi animi rem. Delectus, beatae?</span><span>Maiores blanditiis quibusdam ut dicta nemo aperiam, similique optio dolor quisquam necessitatibus provident maxime quia voluptates aspernatur modi ipsum voluptatum voluptas officia id vel, exercitationem dignissimos! Voluptatem ipsam impedit quos?</span><span>Accusantium atque maiores obcaecati sequi sint aliquid animi dolore veritatis, pariatur dolor quasi nihil tenetur placeat itaque similique, unde ipsa porro nesciunt, minima optio perferendis tempora. Neque praesentium ullam laudantium!</span></p>`
        },
        {
            id:2,
            title:'Android Development',
            description:`Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod eaque, incidunt dignissimos temporibus quos repudiandae eveniet. Tenetur doloribus autem eaque, animi doloremque alias! Modi dolor laboriosam enim fugiat? Libero, vel.</span><span>Recusandae fugiat quidem nulla distinctio consequatur inventore repellendus cupiditate atque suscipit blanditiis, excepturi soluta. Consequatur, sunt harum? Minus ut dicta omnis, libero ratione facere tempora saepe laboriosam, officiis possimus vero.</span><span>Eligendi, et doloremque molestias rerum itaque nisi consequatur eos ut, sunt doloribus in mollitia sapiente maiores aliquam quas ipsam maxime sequi consectetur quo ab magni pariatur laboriosam fuga? Sapiente, animi.</span><span>Animi corrupti culpa exercitationem quasi corporis, aut itaque ipsam quod voluptates voluptatem dicta eum temporibus cupiditate quam non sunt tempore porro assumenda nostrum debitis! Enim quasi aspernatur aliquid maiores illo?</span><span>Hic ab laudantium ratione voluptas architecto modi quisquam cumque officiis perferendis illum dignissimos quod est magni accusamus nostrum, facere eligendi non ut quia veritatis nihil saepe placeat eveniet nam. Illum.</span><span>Similique repellendus dolore, sunt temporibus provident id cupiditate vitae officiis quisquam, sequi alias! Quibusdam aspernatur, possimus illo sit itaque, minima consequuntur assumenda numquam, odio deleniti alias perferendis voluptatum quas officia.</span><span>Amet ipsam corrupti asperiores ipsa. Sunt commodi dolores eos? Voluptatibus recusandae nihil nulla dolore? Minima assumenda obcaecati earum magni itaque ea id similique, tenetur ullam laborum, esse iusto praesentium voluptas?</span><span>Iusto aliquid, nobis nam sit quia sunt, dolorum accusamus officiis magni molestiae qui, nostrum error maxime quis atque cum optio consequatur cupiditate amet ab quisquam quasi animi rem. Delectus, beatae?</span><span>Maiores blanditiis quibusdam ut dicta nemo aperiam, similique optio dolor quisquam necessitatibus provident maxime quia voluptates aspernatur modi ipsum voluptatum voluptas officia id vel, exercitationem dignissimos! Voluptatem ipsam impedit quos?</span><span>Accusantium atque maiores obcaecati sequi sint aliquid animi dolore veritatis, pariatur dolor quasi nihil tenetur placeat itaque similique, unde ipsa porro nesciunt, minima optio perferendis tempora. Neque praesentium ullam laudantium!</span></p>`
        }
          

        ]
    )
  return(

    <>
    <div className="main-container py-16">
        <h1 className=" text-5xl font-bold text-center underline">My Services</h1>
        <div className="services-container space-x-5 px-8 flex mt-12 ">
            <div className="Service-java cursor-pointer hover:bg-slate-200 bg-slate-100 p-5 text-center shadow-lg rounded-xl space-y-5">
            <i class="fa-brands text-5xl fa-java"></i>
                <h1 className="text-4xl  text-center font-bold">Java Development</h1>
                <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod eaque, incidunt dignissimos temporibus quos repudiandae eveniet. Tenetur doloribus autem eaque, animi doloremque alias! Modi dolor laboriosam enim fugiat? Libero, vel.</span><span>Recusandae fugiat quidem nulla distinctio consequatur inventore repellendus cupiditate atque suscipit blanditiis, excepturi soluta. Consequatur, sunt harum? Minus ut dicta omnis, libero ratione facere tempora saepe laboriosam, officiis possimus vero.</span><span>Eligendi, et doloremque molestias rerum itaque nisi consequatur eos ut, sunt doloribus in mollitia sapiente maiores aliquam quas ipsam maxime sequi consectetur quo ab magni pariatur laboriosam fuga? Sapiente, animi.</span><span>Animi corrupti culpa exercitationem quasi corporis, aut itaque ipsam quod voluptates voluptatem dicta eum temporibus cupiditate quam non sunt tempore porro assumenda nostrum debitis! Enim quasi aspernatur aliquid maiores illo?</span><span>Hic ab laudantium ratione voluptas architecto modi quisquam cumque officiis perferendis illum dignissimos quod est magni accusamus nostrum, facere eligendi non ut quia veritatis nihil saepe placeat eveniet nam. Illum.</span><span>Similique repellendus dolore, sunt temporibus provident id cupiditate vitae officiis quisquam, sequi alias! Quibusdam aspernatur, possimus illo sit itaque, minima consequuntur assumenda numquam, odio deleniti alias perferendis voluptatum quas officia.</span><span>Amet ipsam corrupti asperiores ipsa. Sunt commodi dolores eos? Voluptatibus recusandae nihil nulla dolore? Minima assumenda obcaecati earum magni itaque ea id similique, tenetur ullam laborum, esse iusto praesentium voluptas?</span><span>Iusto aliquid, nobis nam sit quia sunt, dolorum accusamus officiis magni molestiae qui, nostrum error maxime quis atque cum optio consequatur cupiditate amet ab quisquam quasi animi rem. Delectus, beatae?</span><span>Maiores blanditiis quibusdam ut dicta nemo aperiam, similique optio dolor quisquam necessitatibus provident maxime quia voluptates aspernatur modi ipsum voluptatum voluptas officia id vel, exercitationem dignissimos! Voluptatem ipsam impedit quos?</span><span>Accusantium atque maiores obcaecati sequi sint aliquid animi dolore veritatis, pariatur dolor quasi nihil tenetur placeat itaque similique, unde ipsa porro nesciunt, minima optio perferendis tempora. Neque praesentium ullam laudantium!</span></p>
                <button className="px-3 py-3 text-white font-mono bg-blue-500 rounded-full shadow-lg">Check</button>
            </div>
            <div className="services-Android  cursor-pointer hover:bg-slate-200 bg-slate-100 p-5 text-center shadow-lg rounded-xl space-y-5">
            <i class="fa-solid text-5xl fa-mobile-screen-button"></i>
            <h1 className="text-4xl  text-center font-bold">Android Development</h1>
                <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod eaque, incidunt dignissimos temporibus quos repudiandae eveniet. Tenetur doloribus autem eaque, animi doloremque alias! Modi dolor laboriosam enim fugiat? Libero, vel.</span><span>Recusandae fugiat quidem nulla distinctio consequatur inventore repellendus cupiditate atque suscipit blanditiis, excepturi soluta. Consequatur, sunt harum? Minus ut dicta omnis, libero ratione facere tempora saepe laboriosam, officiis possimus vero.</span><span>Eligendi, et doloremque molestias rerum itaque nisi consequatur eos ut, sunt doloribus in mollitia sapiente maiores aliquam quas ipsam maxime sequi consectetur quo ab magni pariatur laboriosam fuga? Sapiente, animi.</span><span>Animi corrupti culpa exercitationem quasi corporis, aut itaque ipsam quod voluptates voluptatem dicta eum temporibus cupiditate quam non sunt tempore porro assumenda nostrum debitis! Enim quasi aspernatur aliquid maiores illo?</span><span>Hic ab laudantium ratione voluptas architecto modi quisquam cumque officiis perferendis illum dignissimos quod est magni accusamus nostrum, facere eligendi non ut quia veritatis nihil saepe placeat eveniet nam. Illum.</span><span>Similique repellendus dolore, sunt temporibus provident id cupiditate vitae officiis quisquam, sequi alias! Quibusdam aspernatur, possimus illo sit itaque, minima consequuntur assumenda numquam, odio deleniti alias perferendis voluptatum quas officia.</span><span>Amet ipsam corrupti asperiores ipsa. Sunt commodi dolores eos? Voluptatibus recusandae nihil nulla dolore? Minima assumenda obcaecati earum magni itaque ea id similique, tenetur ullam laborum, esse iusto praesentium voluptas?</span><span>Iusto aliquid, nobis nam sit quia sunt, dolorum accusamus officiis magni molestiae qui, nostrum error maxime quis atque cum optio consequatur cupiditate amet ab quisquam quasi animi rem. Delectus, beatae?</span><span>Maiores blanditiis quibusdam ut dicta nemo aperiam, similique optio dolor quisquam necessitatibus provident maxime quia voluptates aspernatur modi ipsum voluptatum voluptas officia id vel, exercitationem dignissimos! Voluptatem ipsam impedit quos?</span><span>Accusantium atque maiores obcaecati sequi sint aliquid animi dolore veritatis, pariatur dolor quasi nihil tenetur placeat itaque similique, unde ipsa porro nesciunt, minima optio perferendis tempora. Neque praesentium ullam laudantium!</span></p>
                <button className="px-3 py-3 text-white font-mono bg-blue-500 rounded-full shadow-lg">Check</button>
            
            </div>


        </div>




    </div>
    
    </>

  );


};
 export default Services;